### ISSUE TITLE
Issues with CORS?

### ISSUE THREAD

**Issue by sivakusayan** [FelixRilling/smogon-usage-fetch#10]
I'm getting some issues with CORS on my local development server. I put a bandaid on it by just prefixing the URL in the code with https://cors.io/ (perhaps doing this in the repository would be good too), but would there be a better way?

**Comment by FelixRilling** [comment]
Hi!

The smogon website does *not* set an explicit CORS header, making it use the default - no CORS request allowed. CORS is only an issue when fetching the site from a browser context (which I assume is what you're doing, correct me if I am wrong here; I personally use this library through Node.js without issues) - if this is the only option for you, I fear using a proxy server like the one you linked is the best solution there is.

I am skeptical of using the proxied URL by default, as this assumes that the proxy is a) trustworthy and b) not modifying any response in a way that's different from the original one. I think a good compromise would be adding a note to the documentation; what do you think?

**Comment by sivakusayan** [comment]
Sorry for the late reply. I think that would be a good idea!

Is it possible that I could work on adding an option for a base URL? I haven't really done anything related to open source before, and this seems like a good first issue that I could handle. It's up to you, of course.

**Comment by FelixRilling** [comment]
Absolutely! Go ahead and fork the repo, and create a pull request once you're done.
Tell me when I can support you in any way.

**Comment by FelixRilling** [comment]
Will be fixed with #11
